version: "2"
services:
   php-fpm:
      build:
         dockerfile: Dockerfile
         context: .
      links:
         - mysql:mysql
      command: "php -S 0.0.0.0:8000 /var/www/yohai/public/index.php"
      ports:
         - "8000:8000"
      restart: always
   mysql:
      image: mysql:5.6
      environment:
         MYSQL_ROOT_PASSWORD: secret
         MYSQL_DATABASE: testdb
      restart: always